apiVersion: v1
kind: Pod
metadata:
  name: redis-master
  labels:
    name: redis
    redis-sentinel: "true"
    role: master
  annotations:
    podpreset.admission.kubernetes.io/podpreset-allow-database: "resource version"
spec:
  containers:
    - name: master
      image: kadirzade/redis-alpine:v2
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "0.1"
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
    - name: sentinel
      image: kadirzade/redis-alpine:v2
      env:
        - name: SENTINEL
          value: "true"
      ports:
        - containerPort: 26379
  volumes:
    - name: data
      emptyDir: {}