apiVersion: v1
kind: Pod
metadata:
  name: redis-master
  labels:
    name: redis
    redis-sentinel: "true"
    role: master
spec:
  containers:
    - name: master
      image: kadirzade/redis-alpine:v2
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "0.1"
      volumeMounts:
        - name: data
          mountPath: /redis-master-data
        # - name: passwd-volume
        #   mountPath : /etc/redis-passwd          
    - name: sentinel
      image: kadirzade/redis-alpine:v2
      env:
        - name: SENTINEL
          value: "true"
      ports:
        - containerPort: 26379
  volumes:
    - name: data
      emptyDir: {}
    # - name : passwd-volume 
    #   secret :
    #     secretName : redis-pwd      