apiVersion: v1 
kind: Service 
metadata: 
  name: redis
  namespace: redis
spec: 
  type: ClusterIP
  ports: 
  - port: 6379 
    protocol: TCP 
    targetPort: 6379 
  selector: 
    app: redis 
  sessionAffinity: None 